const english = {
skip:'Skip to content',navAbout:'Association',navSport:'The sport',navDisciplines:'Disciplines',navContact:'Contact',contactCta:'Get in touch ↗',
heroTitle:'Beyond focus.<br>Beyond limits.',heroBody:'Accuracy. Power. Speed.<br>Practical shooting in Korea. Together with KRPSA.',explore:'Discover the sport',meet:'Meet KRPSA →',
aboutTitle:'Korean passion.<br><span class="muted">A world stage.</span>',aboutBody:'KRPSA is the IPSC-affiliated association representing the Republic of Korea. Grounded in safety and sportsmanship, we connect Korea with the world through practical shooting.',affiliation:'Official IPSC affiliation record ↗',affiliationBody:'One sport. Shared standards. A collective challenge.',
value1:'Safety comes first',value1Body:'Every match begins with safety. We stand for a sporting culture built on rules and responsibility.',value2:'A fair challenge',value2Body:'Respect for one another. The same rules for everyone. Sportsmanship at the heart of competition.',value3:'Connected to the world',value3Body:'Connecting Korean athletes and the practical shooting community with the international IPSC stage.',
sportTitle:'One moment.<br>Everything you have.',sportBody:'IPSC stands for International Practical Shooting Confederation. Practical shooting is a dynamic sport that combines accuracy, power and speed across varied courses of fire.',sportLink:'Explore IPSC ↗',accuracy:'Precision in every shot',accuracyBody:'Unwavering focus on the target.<br>Every shot makes a difference.',power:'The balance of performance',powerBody:'Power defined by competition rules.<br>In balance with accuracy and speed.',speed:'Performance against the clock',speedBody:'Decision and movement, together.<br>Performance measured in time.',
disciplinesTitle:'Different disciplines.<br><span class="muted">One competitive spirit.</span>',disciplinesBody:'From Handgun to Action Air.<br>Discover the disciplines of IPSC.',disciplineNote:'An introduction to key IPSC disciplines. Contact KRPSA for disciplines available locally, training and participation.',
handgun:'Handgun',handgunBody:'Practical shooting with a handgun. Athletes combine accuracy and speed across varied stages, with divisions defined by equipment characteristics.',rifle:'Rifle',rifleBody:'A rifle discipline that challenges competitors across courses featuring different target distances and arrangements.',shotgun:'Shotgun',shotgunBody:'Practical shooting with a shotgun. Competitors demonstrate accurate, efficient performance across varied targets and courses.',actionair:'Action Air',actionairBody:'Experience practical shooting principles with airsoft equipment. Accuracy and speed are tested under dedicated IPSC Action Air rules.',rulesLink:'Official rules ↗',
resourcesTitle:'A world of competition.<br>Within reach.',resourceRules:'Official IPSC rule books',resourceCalendar:'International match calendar',resourceResults:'Match information & results',contactTitle:'Your next challenge.<br><span class="muted">Starts with KRPSA.</span>',contactBody:'Get in touch about getting started, association membership, international exchange and competition.',contactSource:'Email listed in the official IPSC regional directory',directorName:'Wontaek Lim',directorBody:'Korea Practical Shooting Association<br>Republic of Korea',backTop:'Back to top ↑',photoCredit:'International match photo: Flocks2025 · CC0',heroAlt:'An athlete competing in an international practical shooting event',flagAlt:'Flag of the Republic of Korea'
};
const koreanDisciplines={handgun:'핸드건',handgunBody:'권총을 사용하는 실용사격 종목입니다. 다양한 스테이지에서 정확도와 속도를 종합적으로 평가하며, 장비 특성에 따라 디비전을 구분합니다.',rifle:'라이플',rifleBody:'소총을 사용하는 종목으로, 서로 다른 거리와 배치의 표적을 포함하는 경기 코스에서 실력을 겨룹니다.',shotgun:'샷건',shotgunBody:'산탄총을 사용하는 종목입니다. 다양한 표적과 경기 구성에 맞춰 정확하고 효율적인 경기 수행 능력을 겨룹니다.',actionair:'액션에어',actionairBody:'에어소프트 장비로 실용사격의 경기 원칙을 경험하는 종목입니다. 독립된 IPSC 액션에어 규정 아래 정확도와 속도를 겨룹니다.',rulesLink:'공식 규정 보기 ↗'};
Object.assign(english,{"navTraining":"Get started","mainTitle":"Two ways to begin.<br><span class=\"muted\">One competitive spirit.</span>","mainBody":"Handgun and Action Air, at the heart of KRPSA.<br>Find your way into practical shooting.","mainHandgun":"Practical shooting with live-fire handguns. Test accuracy and speed across varied stages, with competition divisions defined by equipment.","mainAir":"Practical shooting with airsoft equipment. Develop focus and a feel for competition under dedicated IPSC rules—and take your first step with KRPSA.","divisionCta":"Explore handgun divisions ↓","trainingCta":"Explore beginner training ↓","divisionTitle":"Different equipment. Fair competition.","divisionBody":"Divisions group competitors by equipment characteristics. Here are the key differences.","opticsBody":"A division for handguns with a slide-mounted optical sight. Not restricted to the Production approved list; compensators and barrel ports are not permitted.","productionBody":"For handguns on the IPSC approved Production list. Compete with iron sights and develop your fundamentals within defined equipment limits.","productionOpticsBody":"An approved Production handgun with a slide-mounted optical sight. A production-based platform paired with the sight picture of an optic.","openBody":"A division allowing a wider range of competition equipment, including optical sights and compensators, within the rules.","divisionRules":"Division rules ↗","otherDivisions":"Other divisions include <strong>Standard</strong>, for handguns that fit a prescribed box; <strong>Classic</strong>, for 1911-style single-stack handguns; and <strong>Revolver</strong>, for revolvers.","divisionNote":"A brief introduction to handgun divisions. Check current IPSC rules for equipment eligibility and full conditions. Separate rules apply to Action Air.","trainingTitle":"Your first time?<br><span class=\"muted\">One step at a time.</span>","trainingBody":"From Action Air to Live Fire.<br>Discover the KRPSA three-stage introduction.","step1Caption":"Start with experience","step1Body":"Experience practical shooting with airsoft equipment and get familiar with safe participation and the flow of a match.","step2Caption":"Build on safety","step2Body":"Learn safety principles, range etiquette and range commands as you prepare to participate responsibly.","step3Caption":"Take the next step","step3Body":"Experience live-fire shooting under instruction, connecting the safety principles you have learned with the range environment.","trainingNote":"Contact us on KakaoTalk for dates, venues, participation requirements and membership.","trainingContact":"Training & membership →","contactBody":"From beginner training to association membership. Contact ipsckorea on KakaoTalk to get started.","copyId":"Copy ID","kakaoHelp":"In KakaoTalk, choose Add by ID and search for ipsckorea.","emailLabel":"International exchange & other email inquiries"});
Object.assign(english,{"moreSportsTitle":"A wider world of practical shooting.","moreSportsIntro":"Beyond Handgun and Action Air.<br>More equipment. More ways to compete.","moreSportsNote":"An introduction to international IPSC disciplines. Contact KRPSA for local availability, training and matches.","moreSportName0":"Shotgun","moreSportName1":"Rifle","moreSportName2":"Pistol Caliber Carbine","moreSportName3":"Rimfire rifle","moreSportName4":"Rimfire handgun","moreSportBody0":"A shotgun discipline that tests accuracy and performance across varied targets and courses.","moreSportBody1":"A rifle discipline featuring targets at different distances and positions across a range of stages.","moreSportBody2":"A carbine discipline using pistol-caliber ammunition, with separate divisions for optical and iron sights.","moreSportBody3":"Practical shooting with rimfire rifles, testing accuracy and speed under dedicated IPSC rules.","moreSportBody4":"A discipline for .22LR rimfire handguns, governed by its own competition rules."});
Object.assign(english,{photoCredit:'Photo credits',photoTreatment:'Displayed with responsive cropping and tonal adjustments.'});
const korean={};document.querySelectorAll('[data-i18n]').forEach(el=>{korean[el.dataset.i18n]=el.innerHTML});
const koreanAlts={heroAlt:'브라질 실용사격 대회에 참가한 선수',flagAlt:'대한민국 국기'};
function setLanguage(lang){lang=lang==='en'?'en':'ko';document.documentElement.lang=lang;const status=document.getElementById('copy-status');if(status)status.textContent='';document.querySelectorAll('[data-i18n]').forEach(el=>{el.innerHTML=(lang==='en'?english:korean)[el.dataset.i18n]});document.querySelectorAll('[data-alt]').forEach(el=>{el.alt=(lang==='en'?english:koreanAlts)[el.dataset.alt]});document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));document.dispatchEvent(new Event('languagechange'));document.title=lang==='en'?'KRPSA — Korea Practical Shooting Association':'KRPSA — 대한민국 실용사격의 새로운 기준';try{localStorage.setItem('krpsa-language',lang)}catch{}}
document.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('click',()=>setLanguage(el.dataset.lang)));
let initial='ko';try{initial=localStorage.getItem('krpsa-language')||'ko'}catch{}setLanguage(initial);document.getElementById('year').textContent=new Date().getFullYear();

document.getElementById('copy-kakao').addEventListener('click',async()=>{const en=document.documentElement.lang==='en';const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText('ipsckorea');status.textContent=en?'Copied. Add ipsckorea by ID in KakaoTalk.':'복사했습니다. 카카오톡에서 ID로 친구 추가해 주세요.'}catch{status.textContent=en?'Please copy this ID: ipsckorea':'아이디를 직접 복사해 주세요: ipsckorea'}});

// Hero slideshow: pause on request, reduced motion, hidden tab or offscreen hero.
(()=>{
 const photos=[...document.querySelectorAll('.hero-photo')];
 const buttons=[...document.querySelectorAll('[data-slide]')];
 const toggle=document.querySelector('.slideshow-toggle');
 const counter=document.querySelector('.slide-counter');
 const controls=document.querySelector('.slideshow-controls');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let index=0,paused=reduced.matches,inView=true,timer;
 const ready=i=>photos[i].complete&&photos[i].naturalWidth>0;
 function render(){const en=document.documentElement.lang==='en';photos.forEach((p,i)=>p.classList.toggle('is-active',i===index));buttons.forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===index));b.setAttribute('aria-label',en?`Show photo ${i+1}`:`사진 ${i+1} 보기`)});counter.textContent=`${String(index+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')}`;toggle.textContent=paused?'▶':'Ⅱ';toggle.setAttribute('aria-label',en?(paused?'Play slideshow':'Pause slideshow'):(paused?'슬라이드쇼 재생':'슬라이드쇼 일시정지'));controls.setAttribute('aria-label',en?'Hero photo slideshow':'대문 사진 슬라이드쇼')}
 function schedule(){clearTimeout(timer);if(paused||document.hidden||!inView)return;timer=setTimeout(()=>{for(let step=1;step<photos.length;step++){const next=(index+step)%photos.length;if(ready(next)){index=next;break}}render();schedule()},6000)}
 buttons.forEach((b,i)=>b.addEventListener('click',()=>{if(!ready(i))return;index=i;paused=true;render();schedule()}));
 toggle.addEventListener('click',()=>{paused=!paused;render();schedule()});
 controls.addEventListener('keydown',e=>{if(e.key!=='ArrowRight'&&e.key!=='ArrowLeft')return;e.preventDefault();const direction=e.key==='ArrowRight'?1:-1;const next=(index+direction+photos.length)%photos.length;buttons[next].focus();buttons[next].click()});
 document.addEventListener('visibilitychange',schedule);
 document.addEventListener('languagechange',render);
 reduced.addEventListener('change',()=>{if(reduced.matches){paused=true;render();schedule()}});
 new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;schedule()},{threshold:.05}).observe(document.querySelector('.hero'));
 render();schedule();
})();
